AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: Cloudformation testing kinesis firehose
# Metadata:

# Parameters:

# Mappings:

# Conditions:

Globals:
  Function:
    Timeout: 30

Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Project
          Value: Firehose

  deliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        BucketARN: !GetAtt s3Bucket.Arn
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 1 # Mb
        CompressionFormat: UNCOMPRESSED
        Prefix: processed/ # Prefix added to all files coming from the delivery stream. Not required
        RoleARN: !GetAtt firehoseToS3Role.Arn
        CloudWatchLoggingOptions:
          Enabled: True
          LogGroupName: FirehoseLogGroup/test
          LogStreamName: FirehoseLogStream/fh-lambda-s3
        ProcessingConfiguration:
          Enabled: True
          Processors:
            - Type: Lambda
              Parameters:
                - ParameterName: LambdaArn
                  ParameterValue: !GetAtt streamProcessFunction.Arn
        S3BackupMode: Enabled
        S3BackupConfiguration:
          BucketARN: !GetAtt s3Bucket.Arn
          BufferingHints:
            IntervalInSeconds: 60
            SizeInMBs: 1 # Mb
          CompressionFormat: UNCOMPRESSED
          Prefix: unProcessed/
          RoleARN: !GetAtt firehoseToS3Role.Arn

  firehoseToS3Role:
    Type: "AWS::IAM::Role"
    Properties:
      Tags:
        - Key: Project
          Value: Firehose
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - firehose.amazonaws.com
            Action:
              - "sts:AssumeRole"
            Condition:
              StringEquals:
                "sts:ExternalId": !Ref "AWS::AccountId"
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "*"
                Resource:
                  - "*" # To permissive!

  streamProcessFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      CodeUri: streamProcessor/
      Runtime: python3.7
      Tags:
        Key: Project
        Value: Firehose
      Policies:
        - ComprehendFullAccess

Outputs:
  S3ARN:
    Description: ARN of the bucket
    Value: !GetAtt s3Bucket.Arn
  DeliveryStreamARN:
    Description: ARN of firehose delivert stream
    Value: !GetAtt deliveryStream.Arn
  StreamProcessFunction:
    Description: ARN of the Lambda function processing the stream
    Value: !GetAtt streamProcessFunction.Arn
