AWSTemplateFormatVersion: 2010-09-09

Description: Cloudformation testing kinesis firehose
# Metadata:

# Parameters:

# Mappings:

# Conditions:

Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Project
          Value: Firehose

  deliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamType: DirectPut
      S3DestinationConfiguration:
        BucketARN: !GetAtt s3Bucket.Arn
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 1 # Mb
        CompressionFormat: UNCOMPRESSED
        #Prefix: test/ # Prefix added to all files coming from the delivery stream. Not required
        RoleARN: !GetAtt firehoseToS3Role.Arn
        CloudWatchLoggingOptions:
          Enabled: True
          LogGroupName: FirehoseLogGroup/test
          LogStreamName: FirehoseLogStream/test

  firehoseToS3Role:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - firehose.amazonaws.com
            Action:
              - "sts:AssumeRole"
            Condition:
              StringEquals:
                "sts:ExternalId": !Ref "AWS::AccountId"
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "*"
                Resource:
                  - "*" # To permissive!

Outputs:
  S3ARN:
    Description: ARN of the bucket
    Value: !GetAtt s3Bucket.Arn
  DeliveryStream:
    Description: Name of firehose delivery stream
    Value: !Ref deliveryStream
